setup: true
version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  format-code:
    docker:
      - image: cimg/node:16.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:42:58:59:a3:a0:f2:43:a6:ff:4d:27:23:e5:0d:48"
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Format code
          command: npm run format || echo ""
      - run:
          name: Configure git
          command: |
            git config user.email "ready-ci-bot@ready.com"
            git config user.name "CircleCI Job"
      - run:
          name: Commit changes
          command: |
            git commit -am "Format code [skip ci]" || 
            echo "No changes to commit"
      - run:
          name: Push changes
          command: git push origin $CIRCLE_BRANCH

  build-and-test:
    docker:
      - image: cimg/node:16.10
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  setup:
    jobs:
      - format-code
      - build-and-test:
          requires:
            - format-code
      - aws-ecr/build-and-push-image:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
          repo: ready-app
          tag: "backend,latest,v0.1.${CIRCLE_BUILD_NUM}"
          path: .
          requires:
            - build-and-test
