version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  continuation: circleci/continuation@0.2.0

jobs:

workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: '.circleci/main.yml'
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
                  then
                    RUN_BUILD=false
                  else
                    RUN_BUILD=true
                  fi
                  echo '{ "run_build": '$RUN_BUILD' }' >> /home/circleci/params.json
