version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0

jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
  test-e2e:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test:e2e
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
  codecov:
    docker:
      - image: cimg/node:16.10
    steps:
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  sample:
    jobs:
      - build
      - test
      - test-e2e
