version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  continuation: circleci/continuation@0.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run E2E tests
          command: npm run test:e2e
      - run:
          name: Run test coverage
          command: npm run test:cov
      - codecov/upload:
          token: CODECOV_TOKEN
      - asd

  asd:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Test
          command: echo $CIRCLE_PULL_REQUEST

workflows:
  backend-workflow:
    jobs:
      - build-and-test
