setup: true
version: 2.1

orbs:
  node: circleci/node@4.7
  continuation: circleci/continuation@0.2.0

jobs:
  before:
    docker:
      - image: cimg/node:16.10
    steps:
      - run:
          name: asd
          command: echo "asdf"

workflows:
  setup:
    jobs:
      - before
      - continuation/continue:
          requires:
            - before
          configuration_path: '.circleci/main.yml'
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
                  then
                    RUN_BUILD=false
                  else
                    RUN_BUILD=true
                  fi
                  echo $RUN_BUILD
                  echo '{ "run_build": '$RUN_BUILD' }' >> /home/circleci/params.json
