version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  docker: circleci/docker@2.2.0

parameters:
  run_build:
    type: boolean
    default: false

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          no_output_timeout: 30m
          command: |
            TEST=$(circleci tests glob ".spec.ts$" | circleci tests split --split-by=timings)
            npm run test:cov --forceExit $TEST
      - run:
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - run:
          name: Run E2E tests
          command: npm run test:e2e
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  version: 2

  on-pull-request-open:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build-and-test
      - docker/publish:
          deploy: true
          image: ghcr.io/14A-D-Ready-team/backend:0.0.1
          registry: ghcr.io
          docker-username: GHCR_USERNAME
          docker-password: GHCR_TOKEN
