version: 2.1

parameters:
  run_build:
    type: boolean
    default: false

jobs:
  do_something:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: something
          command: echo 'You get the picture'

workflows:
  version: 2

  whence-pr:
    when: << pipeline.parameters.run_build >>
    jobs:
      - do_something:
          name: something
