version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  aws-ecr: circleci/aws-ecr@8.2.1

parameters:
  run_build:
    type: boolean
    default: false

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  version: 2.1

  on-pull-request-open:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - master
          repo: ready-app
          tag: "backend,latest,v0.1.${CIRCLE_BUILD_NUM}"
          path: .
          requires:
            - build-and-test
